### ISSUE TITLE
As a user, I would like to see a button to purchase a Christmas tree permit.

### ISSUE THREAD

**Issue by bryanmcfadden** [nciinc/fs-intake-module#138]
## Notes
For the purposes of usability testing, it would be helpful to give users a way to navigate to the purchase form from the tree guidelines webpage by adding a button.

## Acceptance Criteria
- [ ] user can see a button that starts the flow

## Tasks
- [ ] design button and placement of the button (Bryan)
- [ ] approve design
- [ ] Add a button to the tree guidelines page that navigates to the permit purchase page. (Cameron)

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by bryanmcfadden** [comment]
Here are 3 different design patterns for the permit purchase button placement.

**Proposal 1**
Allows the season dates and purchase button to be placed in the left TOC menu. On mobile devices, the purchase permit button would be the first menu item within the list. The main advantage to this design, is that when the permits are not being sold, the button and background can be hidden. (The menu will just move up)

![proposal 1](https://user-images.githubusercontent.com/16689692/33725832-50703d74-db41-11e7-9d66-0f2c235675fa.png)


**Proposal 2**
The purchase permit button is placed at the top of the information page. The main disadvantage of this design, is that the permit purchase button is only available on the Christmas tree information page.

![proposal 2](https://user-images.githubusercontent.com/16689692/33726059-f67d6afc-db41-11e7-832a-eed0bab76334.png)


**Proposal 3**
This design replaces the "Rules to know" menu item with the "buy permit now" option. The rules are then posted above the permit purchase button. (the lorem ipsum content will be replaced with a small intro to buying a permit and the rules). Th advantage of this design is that it allows users to get to the button from any page (since its in the menu) and forces the rules to be shown before purchasing the permit.

![proposal 3](https://user-images.githubusercontent.com/16689692/33726473-229c5228-db43-11e7-860a-c9c0c2ea26d9.png)

**Comment by cameronwolf** [comment]
@MelissaBraxton @trammell @JaneZC Any opinions on which of these options would be the best or preferred to implement?

**Comment by trammell** [comment]
My favorite option is the one where you find the right Trammell to include on these message (i.e. not me).

**Comment by cameronwolf** [comment]
@MelissaBraxton @JaneZC @ASprinkle @tram I have implemented the three proposals that Bryan created. Here is how they look in the application. What do y'all think of these? Which do you think we should go with, or is there anything that should be done differently to get to a final product that would work well? Thanks!
Proposal 1:
<img width="913" alt="screen shot 2017-12-08 at 2 12 27 pm" src="https://user-images.githubusercontent.com/7295948/33781366-578c2730-dc22-11e7-81d7-77adcaaa7ca0.png">
Proposal 2:
<img width="914" alt="screen shot 2017-12-08 at 2 14 56 pm" src="https://user-images.githubusercontent.com/7295948/33781367-57aaa5fc-dc22-11e7-8158-2abbdd92c1d8.png">
Proposal 3:
<img width="790" alt="screen shot 2017-12-08 at 2 15 34 pm" src="https://user-images.githubusercontent.com/7295948/33781368-57ce90ca-dc22-11e7-8da6-56ef665cef39.png">

**Comment by MelissaBraxton** [comment]
-Remove "now" from the button label.
 - Suggest going with option 2,  but shifting the placement of the button to below the essential information on "when to cut your tree." This info is essential to people knowing whether they'll even be able to use a permit for that location, and unlike the rules info, "when to cut" info will not be repeated between this page and when users actually need to submit their payment.  
 - Not part of acceptance criteria for this story, but I recommend tightening up the "when to cut" content so that it takes up less vertical space so that the user will see the "buy permit" button below this info, but still above the foId. I recall a story re: tightening up the page content/making it more concise/involve less scrolling, but I can't find it now...

**Comment by cameronwolf** [comment]
@MelissaBraxton I have removed 'now' from the label and shifted the button. As far as tightening up the section, doing so will be a bit of a lift and would be beyond the scope of this story. What we recommend doing is usability testing this section and if it does show that there is a benefit to having all the info and the button visible on the screen at the same time then we can go ahead and create a story to work on tightening up the section.

Here is what it looks for a simple date example(Mt Hood):
<img width="600" alt="screen shot 2017-12-08 at 4 03 21 pm" src="https://user-images.githubusercontent.com/7295948/33785124-bb59bda4-dc31-11e7-8aee-599719eda9de.png">

And here is the updated view with a more complex date example(ARP): 
<img width="616" alt="screen shot 2017-12-08 at 4 10 00 pm" src="https://user-images.githubusercontent.com/7295948/33785276-47fa08c2-dc32-11e7-940d-cfe61652343f.png">

**Comment by bryanmcfadden** [comment]
@MelissaBraxton - While in usability testing, there have been several suggestions of showing the dates/times in a 2-column format. This would help tighten up the page while still showing the same amount of information. (see - below)

![138_proposal](https://user-images.githubusercontent.com/16689692/33836611-d748a886-de57-11e7-86a1-eae51f582a19.JPG)

**Comment by cameronwolf** [comment]
Looks like a good way to do it @bryanmcfadden. Since it has come up in usability testing, I created issue #181 to implement this change. @MelissaBraxton, based on my latest screenshots, do I have your approval to open a PR to merge this change into our sprint branch?

**Comment by tram** [comment]
Good idea condensing dates and times into tables. When implementing, recommend placing more weight on the actual dates and times than on the headers (i.e. "Season dates", "Cutting hours").

**Comment by cameronwolf** [comment]
Sounds like that would be helpful for drawing the user's eye to where we need it. I have made a note of that on ticket #181. @tram /@MelissaBraxton  With what I have now, do you approval the design and placement of the button so I can open a PR and merge these changes? Thanks.

**Comment by tram** [comment]
👍 Button looks good. Ship it.
