### ISSUE TITLE
As someone interested in buy a permit, I am required to see the forest rules before I can purchase my permit.

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-intake-module#143]
## Acceptance Criteria
- [ ] The user will be required to review the rules in between filling out my information and being directed to pay.gov to complete my payment. 
- [ ] the user confirms that they have read the rules (require click to the rules before check)
- [ ] after the user confirms, it will direct them to pay.gov
- [ ] User confirmation button is separate from button to click to pay.gov
- [ ] Pay.gov button is not active until user confirms that they've read the rules

## Tasks
- [ ] Change the button language on the adding personal info page to say go read the rules.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by JaneZC** [comment]
@MelissaBraxton @bryanmcfadden @ASprinkle @sethalt 

Here are some initial mockups of this to get everything going; I reviewed with Bryan but wanted to mention that I am not a graphic designer and am sure this is not 100 percent fantabulous. Please adjust, as appropriate. :)

For the purposes of this mockup, I assumed we were pulling from the 'rules to know' section and not creating 'new' content. 

Also, I noticed a few typos in the content, and we should fix those during this sprint. The content, though, was pulled locally so may not be up-to-date with what's on staging. Staging is down so I wasn't able to verify the typos are still on staging, but will do so once this material comes back on staging.

Jane

p.s. @trammell Welcome! I think I'm supposed to tag you as well? If not, feel free to ignore. :)

Upon first reaching the page -

![First Reaching the Page.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/43afcae6-1f58-4e4f-b70f-2d11ca8e3ca4)

![Before checking the box.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/70146be6-8f98-4b23-85a9-b2ddd934d40f)

![After checking the box.png](https://images.zenhubusercontent.com/59e77062a468affe6df72864/f9ba8a5b-9a45-45cb-9f4b-1f0760eda489)

**Comment by sadlerw** [comment]
![Screen Shot 2017-12-07 at 11.24.30 AM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/222a0a8f-8ad0-49b6-acd0-aac09bbc5839)

**Comment by trammell** [comment]
Pretty sure you have the wrong guy!

**Comment by JaneZC** [comment]
@wsadler

The mockup I did was for Arapaho/Roosevelt, and the content on staging doesn't reflect the Pacific Yew being prohibited. Just wanted to make sure that the example above is not for ARP; if its another forest, then the Pacific Yew prohibition language makes sense. 

I don't have a preference on the +/- and defer to @bryanmcfadden or @MelissaBraxton

**Comment by trammell** [comment]
@sadlerw @JaneZC @bryanmcfadden @MelissaBraxton unsubscribe

**Comment by sadlerw** [comment]
latest mockup after color changes:

![Screen Shot 2017-12-07 at 3.36.25 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/b3cbf172-723d-4ab4-984a-f630fe77f1b0)

**Comment by tram** [comment]
Would recommend removing open/close functionality and simply showing Rules & Regs content.

**Comment by tram** [comment]
Recommend adding description to checkbox that says it is required to move forward. Also recommend disabling Checkout box until checkbox is checked.

**Comment by sadlerw** [comment]
I was told that for 508 we don't disable the submit ever.  That allows the users to hit the box then get focused back on the first error to fix @Tram

**Comment by sadlerw** [comment]
After consulting with Jane I've landed on having the rules section open by default and moving the checkbox out to just over the submit button.
![Screen Shot 2017-12-08 at 3.18.50 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/39e62253-0907-40f2-b893-f1df261ff49a)

**Comment by MelissaBraxton** [comment]
A more accessible option: Submit button appears enabled, but when the user tries to click it before they've checked the box, they get a message saying they need to indicate that they've read the rules before they can move forward. Once the user checks the box, the message goes away.

**Comment by sadlerw** [comment]
That's the behavior we have implemented now Melissa.

**Comment by MelissaBraxton** [comment]
Cool!  Can you post a mock that includes the error message?

**Comment by sadlerw** [comment]
Sorry I thought we already had this in here:

![Screen Shot 2017-12-08 at 4.28.11 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/900121fa-25c5-4ecd-b7a6-e9f9633228dc)

**Comment by sadlerw** [comment]
I don't think the page flow has changed since all we added was a new form field. Is there still an update to that needed @MelissaBraxton ? It's the first task.

**Comment by ASprinkle** [comment]
This page works really well. It is clear that you have to not only scroll past the rules and regs before checking the box, but there is a link to take you back there if you're not sure. That is great!
A couple of notes and then I can consider the design approved for this story:
For the Mt. Hood NF the following language in the rules does not apply: "from plantations and previously thinned stands of trees"  This bullet should be removed from Mt. Hood NF.  Many people find their Christmas trees within plantations and previously thinned stands.  If this exists on the Mt. Hood page, then it should be removed earlier - and I apologize for not catching it.
For the following bullet specify height: "The tree must be 12 feet or less <in height, or tall or something to specify height of tree> if permit was purchased on line"

**Comment by MelissaBraxton** [comment]
The task flow model is here: https://app.mural.ly/t/gsa6/m/gsa6/1513030891953/777098c6c7ca20de528e68f3dc78256732e677f9

**Comment by sethalt** [comment]
@MelissaBraxton @ASprinkle Can we get design approval on this task

**Comment by JaneZC** [comment]
@ASprinkle @sadlerw 

Just following up on Amber's comment; I'd go with the below.

"The tree must be 12-feet tall or less if the permit was purchased online."

**Comment by tram** [comment]
The error message should state the benefit from correction. Consider changing message from "Checking that you have viewed the rules is required." to something like "Purchasing a tree permit requires you agree to the rules and regulations."

Also recommend removing open/close functionality and simply showing Rules & Regs content.

**Comment by sethalt** [comment]
@tram 
![localhost_4200_applications_christmas-trees_forests_arp_new](https://user-images.githubusercontent.com/2347759/33953630-3a68aa98-dffb-11e7-86e9-89363b569ead.png)

**Comment by sethalt** [comment]
@tram Can you please approve this design based on the last screenshot. Thanks!

**Comment by MelissaBraxton** [comment]
Two content tweaks, and then I think it's good to go:
 - The first error message: it says "there is an error with your application" is a bit odd, as we've been avoiding the "application" terminology, since folks aren't really applying for anything. But if it's ok with @ASprinkle, then its fine with me. 
 -  The first error message: It says "...before submitting" but the call to action is "checkout" (not submit). I'd suggest changing it to "...before you checkout."
 - Checkbox messaging: the language next to the check box should agree with the language of the error message. Right now its a bit odd that a user checks the box to say they've "read and understood" but the error message says they "agree," which is a bit different.  

IANAL, but all 4 of the LEOs I've interviewed this week have mentioned that the permit is like a contract and that permit holders must agree to the terms. Suggest adding the word "agreed" to the text next to the check box. Something like "I've read, understood, and agreed to the rules..."
 - Number of permits: I just want to double check--is it really 5 per household or 5 per person? @ASprinkle and @JaneZC

**Comment by ASprinkle** [comment]
Is the error with processing the permit, or is with the information they have provided? I would like to avoid the "application" terminology where possible.  Instead - if appropriate use "there is an error with processing your permit" might be better suited.  
and it really is 5 per "household" which is an ODD measure - and not really enforced ever.  I don't know who thought of it - but it would be very hard to track.  We will need to stay consistent with the terminology the forests provide, and maintain the "household" description.

**Comment by JaneZC** [comment]
@ASprinkle @MelissaBraxton On the checkbox messaging ... the original language I suggested was a bit more formal; I believe it was defaulted to the language in the story's tasks. 

The language I had was:

By checking this box, I acknowledge that I have read, understand, and agree to the Christmas tree permit rules and regulations.

My preference would be to use this language. I think we need to be clear that they must act (ie. check the box) and that by doing so they know what is happening (read understand and agree). It is a bit redundant, but I would also recommend that we specify that this is for the Christmas tree permits. So ... that's how I came up with the language. :)

**Comment by sadlerw** [comment]
![Screen Shot 2017-12-14 at 1.31.04 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/eed8cb6c-e121-4402-aa99-d1e10840f6dd)

![Screen Shot 2017-12-14 at 1.30.50 PM.png](https://images.zenhubusercontent.com/595e640361b4ca3b0a7370e7/1953213b-65f4-43cd-b967-1fed496b9592)

**Comment by MelissaBraxton** [comment]
LGTM!

**Comment by JaneZC** [comment]
@MelissaBraxton @ASprinkle @sethalt In reviewing the content this weekend, I had two last-minute suggestions on the Buy a Permit page. If its too late for this sprint, perhaps we can add to a future story?

1) The "By checking this box ... " paragraph should be moved above the Pay.gov paragraph to make it clearer that it applies to the content right above it. Its a bit disjointing to switch from the rules, to pay.gov with references the checkout button, then back to the rules, and then to Checkout button. We've also removed all of the design/section separators so content is tending to run together, which makes organization of the content more important.

Also, with the checkbox where it is and nothing indicating content is 'grouped together' somehow ... it may appear as if the entire form (incl. first name, last name, email, the pay.gov redirect, etc.) are the 'rules and regulations.' @bryanmcfadden Maybe something worth testing?

2) I think when we removed the drop-down bar, the header "Permit Rules and Regulations" was removed and then replaced with the less formal "Rules to Know." Since we are dealing with what law enforcement views as a contractual type of situation, I would opt for the more formal wording here, and, in particular, use wording that matches with what is in the official acceptance language. Can we change the header of this section to Permit Rules and Regulations?

There are other content changes that I think are needed to this section (ie. consistency in phrasing between bullet points and headers, etc.), but I think that can wait for a future story? I know @bryanmcfadden added a story (#162) and this could be addressed as part of that.

As a side note ... and just something I have to say ... I have a personal and longstanding crusade against starting any sentence or a header with the word IT. (I consider it lazy writing.) I would strongly advocate for removing that from the subhead as part of Story #162. :)

**Comment by tram** [comment]
👍 Good catch moving the confirmation checkbox next to the appropriate content. Ship it.
🤔 The concern about using a phrase like "Permit Rules and Regulations" as a header for something we want someone to read is that "rules and regulations" is often code for "things our lawyers made us put in and is probably okay to skip". If it needs to be reinforced that these are contractually obligated by law enforcement, that can happen in the confirmation checkbox. That said, if it's necessary to signal this _before_ reading, if these rules are repeated in another context—on the printed permit, for example—that should help alleviate any blindness to legalese.

**Comment by lpendem** [comment]
@JaneZC @tram Here is the updated screen with the change, please review and `approve` if this meets the acceptance criteria.
![screen shot 2017-12-21 pm](https://user-images.githubusercontent.com/7645088/34118861-2039ceb2-e3ee-11e7-9702-d8c08c213a7c.png)

**Comment by ASprinkle** [comment]
I am ok with this change.  We should make sure that "Rules to Know" is consistent throughout the rest of the site.  We should not mix different kinds of rules headers throughout the pages.  SO the hyperlink by the checkbox should have the same language as the header.
As far as design approval - no name is attached to the task. From my perspective this page is set up really well for accomplishing the goal of the story once the hyperlink text is updated.

**Comment by lpendem** [comment]
@ASprinkle @MelissaBraxton @tram screen shot with the updated link text. Please provide feedback/approval (add name next to the design approval task on the card)
<img width="456" alt="screen shot 2017-12-18 at 4 31 21 pm" src="https://user-images.githubusercontent.com/7645088/34129190-3d267b88-e411-11e7-957d-22dc0b885e28.png">

**Comment by lpendem** [comment]
@ASprinkle @MelissaBraxton I didn't realize the text was changed earlier in this thread, here is the updated screen: 
<img width="480" alt="screen shot 2017-12-18 at 5 24 27 pm" src="https://user-images.githubusercontent.com/7645088/34131119-5567905e-e418-11e7-9aea-10d545b6e41b.png">

**Comment by MelissaBraxton** [comment]
Thanks Shekar. I believe @tram is out for the rest of the day, so I'm hopping in here. I approve.
