### ISSUE TITLE
As a tech person, I want to have docker builds tested during circle build by testing application using docker commands

### ISSUE THREAD

**Issue by cameronwolf** [nciinc/fs-intake-module#162]
## Acceptance Criteria
- [ ] Test commands are run inside of docker-compose images

## Tasks
- [ ] Update commands on circle build to be run against docker images rather that application on circle

## Definition of Done
- [ ] Internal team code review
- [ ] Docker updated
