### ISSUE TITLE
As an e-Permits content admin, I would like a consistent way to update Forest's information in response to change requests. 

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-intake-module#367]
### Notes 
Exactly who will fill this role is still unclear, but this will be the person tasked with making changes/responding to Forest's requests to edit content on their Forest page. We're assuming this person will know or learn GitHub and know how to edit html, some familiarity with angular, and edit json.

### Acceptance criteria
 - [x] FS Admin's process for updating/changing all types of content (with the exception of cutting season dates/times) is consistent. 
 -  [x] Create a readme/ or a wiki page about how each content section element in the tree guidelines is generated.
  - [x] Content admins should be able to tell which data is forest specific and which is pulled from a central database

### Tasks
- [x] determine if the standardization of rules between forests has more weight than making each forest's data as flexible as possible
- [x] determine advantages/disadvantages of json and markdown for data and templates
- [x] Do a trial run of markdown implementation with "how to plan your trip" section (seth)
- [x] add markdown for `how to cut your tree` (shekar)
- [x] add markdown for `rules to know` (seth)
- [x] add markdown for `when to cut your tree` (seth)
- [x] add markdown for `where to find your tree` (will)
- [x] add markdown for `contact us` (cameron)
- [x] server code changes - remove seeders, change migrations, remove models and update controller (shekar)
- [x] Integration tests to test all admin routes 
- [x] Figure out solution for link to map on how to plan your trip section because we can't link to anchors on the page with markdown. (seth)
- [x] consider refactoring components and views into a more human parseable structure
- [x] research markdown as a way to take static template html out of the component templates
- [x] simplify tree guidelines dir structure (seth)
- [x] instructional document in README with database update, json update, markdown update instructions and detail of overall organization and function (will)
- [x] fix bug for anchor in url not loading (cameron)
- [x] PR comment -  tree application form mock forest factory (will)
## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [ ] fix rules variable interpolationon form (will)
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Thank you for making this story.  Would the follow on to this be, "so that I know what information I can request updates for."?

**Comment by sethalt** [comment]
ng2 markdown https://www.npmjs.com/package/ngx-md
