### ISSUE TITLE
Update forest locations data to make them consistent across different sections

### ISSUE THREAD

**Issue by lpendem** [nciinc/fs-intake-module#80]
## Notes
Road numbers are listed as just numbers in "Roads to try" section, but they are prefixed with "Road/Highway" in other sections. 

## Acceptance Criteria
- [ ]

## Tasks
- [ ] update seeders data for forest-locations

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by rrefoy** [comment]
@lpendem @sadlerw can you update this to be written in terms of user value?

**Comment by sadlerw** [comment]
This was done as part of #93.  You can cancel it @rrefoy

**Comment by rrefoy** [comment]
cc: @ASprinkle
