### ISSUE TITLE
As a forest service employee, when I make a change I would like to see changes made to the website deployed quickly

### ISSUE THREAD

**Issue by lauraGgit** [nciinc/fs-intake-module#81]
## Notes
Bump up the CI build from Circle 1.0 to 2.0

## Acceptance Criteria
- [ ] When a CI builds it is on circle 2.0

## Tasks
- [ ] 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
